name: catal
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - numpy=1.14.5
  - requests=2.19.1
  - urllib3=1.23
  - ipython=6.5.0
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - pandas=0.23.0
  - pillow=5.1.0
  - pip=10.0.1
  - python=3.6.5
  - tensorboard=1.8.0
  - tensorboardx=1.2
  - tensorflow=1.8.0
  - tqdm=4.23.4
  - pytorch=0.4.0
  - torchvision=0.2.1
  - pip:
    - torch==0.4.0
